language: c

sudo: false

env:
  global:
    - LUAROCKS=2.2.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit

branches:
  only:
    - master

before_install:
  - bash .travis/setup_uv.sh
  - source .travis/setenv_lua.sh

install:
  - sudo luarocks make rockspecs/lluv-scm-0.rockspec UV_DIR=$TRAVIS_BUILD_DIR/libuv

before_script:
  - luarocks install lunitx
  - luarocks install luafilesystem
  - luarocks install lua-path
  # - sudo pip install cpp-coveralls

script:
  - cd test
  - lua test-close.lua
  - lua test-active.lua
  - lua test-multi-write.lua
  - lua test-spawn.lua
  - lua test-gc-basic.lua
  - lua test-gc-timer.lua
  - lua test-gc-tcp.lua
  - lua test-data.lua
  - lua test-udp-send-ctx.lua
  - lua -e"require'lluv.utils'.self_test()"
  - lunit.sh test-fs.lua
  - lunit.sh test-defer-error.lua
  - cd ./luasocket
  - lua testsrvr.lua > /dev/null &
  - lua corun.lua testclnt.lua
  - lua ts.lua > /dev/null &
  - lua defer_error.lua

# after_success:
#   - coveralls -b .. -r .. --dump c.report.json
#   - luacov-coveralls -j c.report.json

notifications:
  email:
    on_success: change
    on_failure: always
